-- schema.sql
-- Run this script in the SQL Editor of your Supabase project (https://database.new)

-- 1. Create registrations table
CREATE TABLE IF NOT EXISTS registrations (
  id TEXT PRIMARY KEY,
  nom TEXT NOT NULL,
  prenom TEXT NOT NULL,
  "dateNaissance" TEXT,
  sexe TEXT,
  niveau TEXT,
  discipline TEXT,
  licencie TEXT,
  "numeroLicence" TEXT,
  "engagementLicence" BOOLEAN DEFAULT false,
  club TEXT,
  "categoriePoids" TEXT,
  email TEXT,
  telephone TEXT,
  "consentementRGPD" BOOLEAN DEFAULT false,
  "dateInscription" TEXT,
  "photoUrl" TEXT
);

ALTER TABLE registrations ADD COLUMN IF NOT EXISTS "photoUrl" TEXT;

-- Enable RLS for registrations
ALTER TABLE registrations ENABLE ROW LEVEL SECURITY;

-- Allow public read/write access to registrations
DROP POLICY IF EXISTS "Public registrations policy" ON registrations;
CREATE POLICY "Public registrations policy" ON registrations
  FOR ALL USING (true) WITH CHECK (true);

-- 2. Create matches table
CREATE TABLE IF NOT EXISTS matches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT,
  sexe TEXT,
  "categoriePoids" TEXT,
  niveau TEXT,
  fighter1 JSONB,
  fighter2 JSONB,
  sort_order INTEGER,
  match_number INTEGER,
  tier TEXT,
  winner TEXT
);

-- Migration: add poster/result columns if table already exists
ALTER TABLE matches ADD COLUMN IF NOT EXISTS match_number INTEGER;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS tier TEXT;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS winner TEXT;

-- Enable RLS for matches
ALTER TABLE matches ENABLE ROW LEVEL SECURITY;

-- Allow public read/write access to matches
DROP POLICY IF EXISTS "Public matches policy" ON matches;
CREATE POLICY "Public matches policy" ON matches
  FOR ALL USING (true) WITH CHECK (true);

-- 3. Create match_metadata table (timestamps + publication site public)
-- Clés utilisées : matches_timestamp, matches_published (true/false), matches_published_at (ISO)
CREATE TABLE IF NOT EXISTS match_metadata (
  key TEXT PRIMARY KEY,
  value TEXT
);

-- Enable RLS for match_metadata
ALTER TABLE match_metadata ENABLE ROW LEVEL SECURITY;

-- Allow public read/write access to match_metadata
DROP POLICY IF EXISTS "Public match_metadata policy" ON match_metadata;
CREATE POLICY "Public match_metadata policy" ON match_metadata
  FOR ALL USING (true) WITH CHECK (true);
